/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import tmodelXtext.ui.internal.TmodelXtextActivator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TmodelXtextActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
