/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getLoaderAccess().getGroup(), "rule__Loader__Group__0");
			builder.put(grammarAccess.getLoaderAccess().getGroup_4(), "rule__Loader__Group_4__0");
			builder.put(grammarAccess.getLoaderAccess().getGroup_4_3(), "rule__Loader__Group_4_3__0");
			builder.put(grammarAccess.getLoadModelAccess().getGroup(), "rule__LoadModel__Group__0");
			builder.put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
			builder.put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
			builder.put(grammarAccess.getColumnAccess().getGroup_4(), "rule__Column__Group_4__0");
			builder.put(grammarAccess.getAddAccess().getGroup(), "rule__Add__Group__0");
			builder.put(grammarAccess.getDeleteAccess().getGroup(), "rule__Delete__Group__0");
			builder.put(grammarAccess.getUpdateAccess().getGroup(), "rule__Update__Group__0");
			builder.put(grammarAccess.getLoaderAccess().getLoadmodelAssignment_3(), "rule__Loader__LoadmodelAssignment_3");
			builder.put(grammarAccess.getLoaderAccess().getOperationAssignment_4_2(), "rule__Loader__OperationAssignment_4_2");
			builder.put(grammarAccess.getLoaderAccess().getOperationAssignment_4_3_1(), "rule__Loader__OperationAssignment_4_3_1");
			builder.put(grammarAccess.getLoadModelAccess().getUrlAssignment_1(), "rule__LoadModel__UrlAssignment_1");
			builder.put(grammarAccess.getTableAccess().getNameAssignment_3(), "rule__Table__NameAssignment_3");
			builder.put(grammarAccess.getColumnAccess().getNameAssignment_3(), "rule__Column__NameAssignment_3");
			builder.put(grammarAccess.getColumnAccess().getTableNameAssignment_4_1(), "rule__Column__TableNameAssignment_4_1");
			builder.put(grammarAccess.getAddAccess().getTableAssignment_3(), "rule__Add__TableAssignment_3");
			builder.put(grammarAccess.getAddAccess().getColumnAssignment_4(), "rule__Add__ColumnAssignment_4");
			builder.put(grammarAccess.getDeleteAccess().getTableAssignment_3(), "rule__Delete__TableAssignment_3");
			builder.put(grammarAccess.getDeleteAccess().getColumnAssignment_4(), "rule__Delete__ColumnAssignment_4");
			builder.put(grammarAccess.getUpdateAccess().getTableAssignment_2(), "rule__Update__TableAssignment_2");
			builder.put(grammarAccess.getUpdateAccess().getColumnAssignment_3(), "rule__Update__ColumnAssignment_3");
			builder.put(grammarAccess.getUpdateAccess().getNewNameAssignment_5(), "rule__Update__NewNameAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
